### ISSUE TITLE
Is there any list of apps using this api? 

### ISSUE THREAD

**Issue by danielo515** [C-D-Lewis/dash-api#1]
Hello, 

This API is very promising, however seems that no watchface is using it. Do you have any list of whatch faces using it? 

Thanks and regards

**Comment by C-D-Lewis** [comment]
My own faces Dual Gauge and Eventful, Snowy, at least. I need analytics on who is invoking it...

**Comment by C-D-Lewis** [comment]
I have started a known apps list in the README.md file, let me know if you find anymore. If I find some, I'll add them here.

**Comment by danielo515** [comment]
Thank you! That is definitely better than nothing!
